import React, { createContext, useContext, useState } from 'react';

export type Lang = 'tj' | 'ru' | 'en';

const T = {
  en: {
    home: 'Home', catalog: 'Catalog',
    searchPlaceholder: 'Search laptops by brand, model or CPU…',
    lightMode: 'Light Mode', darkMode: 'Dark Mode', profile: 'Profile',
    badge: 'Tajikistan Laptop Platform',
    heroTitle1: 'The best laptop', heroTitle2: 'at somoni price', heroTitle3: 'in Tajikistan',
    heroDesc: 'Somon Comp — global laptop marketplace in Tajikistan. Clear TJS pricing, official warranty, and fast delivery.',
    viewCatalog: 'View Catalog', learnMore: 'Learn More',
    weekOffer: 'Week\'s Pick', available: 'Available', viewAll: 'View All →',
    modelsInStock: 'Models in stock', topBrands: 'Top brands', avgWarranty: 'Avg warranty', localCurrency: 'Local currency',
    popular: 'Popular', topSales: 'Top Sales Laptops',
    whySomon: 'Why Somon Comp', lessProblems: 'Less hassle.', moreLaptops: 'More laptop.', allInOnePlace: 'Everything in one place and clear.',
    somoniPrice: 'Priced in Somoni', somoniPriceDesc: 'Clear TJS pricing, no hidden import fees. What you see is exactly what you pay.',
    officialWarranty: 'Official Warranty', officialWarrantyDesc: 'Every laptop ships with a manufacturer warranty honored right here in Tajikistan.',
    fastDelivery: 'Fast Delivery', fastDeliveryDesc: 'Same-week delivery across Dushanbe with reliable nationwide shipping on all orders.',
    laptopCatalog: 'Laptop', catalogSuffix: 'Catalog',
    found: 'found', laptopWord: 'laptop',
    priceInTJS: 'Price (TJS)', filtersLabel: 'Filters', brand: 'Brand', ram: 'RAM',
    resetFilters: 'Reset all filters', showFilters: 'Show Filters', hideFilters: 'Hide Filters', active: 'Active',
    noLaptopsFound: 'No laptops found', tryChangingFilters: 'Try changing your filters or search term.',
    recommendedForYou: 'Recommended for you',
    inStock: 'in stock', outOfStock: 'Out of stock', buy: 'Buy Now', warranty: 'mo warranty',
    backToCatalog: '← Back to catalog', specifications: 'Specifications',
    processor: 'Processor', memory: 'Memory', storage: 'Storage', graphics: 'Graphics',
    warrantyLabel: 'Warranty', keyboardLayout: 'Keyboard',
    addToCart: 'Buy Now', outOfStockBtn: 'Out of Stock',
    descriptionLabel: 'Description', relatedLaptops: 'You might also like',
    guarantee: '12–24 month warranty', deliveryCity: 'Delivery in Dushanbe', modelsCount: '22+ models',
    notifTitle: 'Notifications',
    notif1Title: 'New laptops added!', notif1Desc: 'MSI Pulse 15 & MacBook Pro M3 now in stock',
    notif2Title: 'Price drop on Acer Aspire 3', notif2Desc: 'Now from 4,990 TJS',
    notif3Title: 'Free delivery in Dushanbe', notif3Desc: 'On all orders this week',
    months: 'mo', monthsFull: 'months',
    installmentLabel: 'Installment Options',
    monthsText: 'months',
    monthlyPay: 'Monthly payment',
    paymentPartner: 'Select payment partner',
    payMethodAlif: 'Installment via Alif Salom (up to 24 months) or pay instantly using Alif Mobi.',
    payMethodHumo: 'Pay in installments via Humo card or instantly using Humo Online.',
    payMethodEskhata: 'Installments and quick scanning payments via Eskhata Mobile.',
    payMethodDC: 'Scan QR code to pay instantly with Dushanbe City wallet.',
    login: 'Log In', signup: 'Sign Up', logout: 'Log Out',
    emailLabel: 'Email', passwordLabel: 'Password', confirmPasswordLabel: 'Confirm Password',
    noAccount: 'Don\'t have an account?', haveAccount: 'Already have an account?',
    createAccount: 'Create Account', welcomeBack: 'Welcome back',
    loginToContinue: 'Log in to manage your brand and listings.',
    signupToStart: 'Create an account to start selling your own laptop brand.',
    passwordsNoMatch: 'Passwords do not match',
    myProfile: 'My Profile', memberSince: 'Member since', accountInfo: 'Account Info',
    myListings: 'My Listings', addLaptopListing: 'Add a Laptop Listing',
    brandName: 'Brand name', modelNameLabel: 'Model name', cpuLabel: 'CPU', gpuLabel: 'GPU (optional)',
    ramLabel: 'RAM (GB)', storageLabel: 'Storage (GB)', priceLabel: 'Price (TJS)',
    stockLabel: 'Stock quantity', warrantyMonthsLabel: 'Warranty (months)', keyboardLayoutLabel: 'Keyboard layout',
    descriptionOptional: 'Description (optional)', submitListing: 'Add Listing',
    submitting: 'Adding…', listingAdded: 'Listing added!', noListingsYet: 'You haven\'t added any laptops yet.',
    requiredField: 'Required',
    invalidCredentials: 'Invalid email or password', signupFailed: 'Could not create account. Email may already be in use.',
    listingFailed: 'Could not add listing. Check the fields and try again.',
    adminPanel: 'Admin Panel', manageListings: 'Listings', manageUsers: 'Users',
    ownerLabel: 'Owner', actionsLabel: 'Actions', editAction: 'Edit', deleteAction: 'Delete',
    saveAction: 'Save', cancelAction: 'Cancel',
    confirmDeleteListing: 'Delete this listing? This cannot be undone.',
    confirmDeleteUser: 'Delete this user? This cannot be undone.',
    activateAction: 'Activate', deactivateAction: 'Deactivate',
    makeAdminAction: 'Make Admin', revokeAdminAction: 'Revoke Admin',
    statusLabel: 'Status', roleLabel: 'Role', adminRole: 'Admin', userRole: 'User', youLabel: '(you)',
    noListingsAdmin: 'No laptop listings yet.', noUsersFound: 'No users found.', inactiveLabel: 'Inactive',
    usernameLabel: 'Username', phoneLabel: 'Phone number', addressLabel: 'Address',
    usernameAvailable: 'Username is available', usernameTaken: 'Username is taken. Try one of these:',
    checkingUsername: 'Checking…', saveProfile: 'Save changes', profileUpdated: 'Profile updated.',
    profileUpdateFailed: 'Could not update profile.',
    myBrands: 'My Brands', registerBrand: 'Register a Brand', noBrandsYet: 'You haven\'t registered a brand yet.',
    registerBrandFirst: 'Register a brand before adding a listing.',
    brandOnboardingTitle: 'Register Your Brand', brandOnboardingDesc: 'Tell us about your brand so buyers know who they\'re dealing with.',
    contactPhoneLabel: 'Contact phone', supportEmailLabel: 'Support email', brandDescriptionLabel: 'Brand description',
    submitBrand: 'Register Brand', brandRegistered: 'Brand registered!', brandRegisterFailed: 'Could not register the brand.',
    selectBrand: 'Select a brand', quantityLabel: 'Quantity', recordSale: 'Record Sale', saleRecorded: 'Sale recorded!',
    saleRecordFailed: 'Could not record the sale.',
    overviewTab: 'Overview', totalRevenue: 'Total Revenue', totalSales: 'Total Sales', totalListings: 'Total Listings',
    aiAssistant: 'AI Assistant',
    totalUsers: 'Total Users', revenueTrend: 'Revenue Trend', brandPerformance: 'Brand Performance',
    myStatsTitle: 'My Brand Stats', myStatsDesc: 'Performance for your own listings only.',
    notificationsEmpty: 'No notifications yet.', noSalesDataYet: 'No sales data yet.',
    noUsernameSet: 'no username set',
  },
  ru: {
    home: 'Главная', catalog: 'Каталог',
    searchPlaceholder: 'Поиск ноутбуков по бренду, модели или процессору…',
    lightMode: 'Светлая тема', darkMode: 'Тёмная тема', profile: 'Профиль',
    badge: 'Ноутбучная платформа Таджикистана',
    heroTitle1: 'Лучший ноутбук', heroTitle2: 'по цене в сомони', heroTitle3: 'в Таджикистане',
    heroDesc: 'Somon Comp — мировой рынок ноутбуков в Таджикистане. Чёткие цены в TJS, официальная гарантия и быстрая доставка.',
    viewCatalog: 'Смотреть каталог', learnMore: 'Узнать больше',
    weekOffer: 'Выбор недели', available: 'В наличии', viewAll: 'Смотреть все →',
    modelsInStock: 'Моделей в наличии', topBrands: 'Топ брендов', avgWarranty: 'Средняя гарантия', localCurrency: 'Местная валюта',
    popular: 'Популярное', topSales: 'Топ продаж ноутбуков',
    whySomon: 'Почему Somon Comp', lessProblems: 'Меньше проблем.', moreLaptops: 'Больше ноутбуков.', allInOnePlace: 'Всё в одном месте и понятно.',
    somoniPrice: 'Цены в сомони', somoniPriceDesc: 'Чёткие цены в TJS без скрытых ввозных сборов. Что видите — то и платите.',
    officialWarranty: 'Официальная гарантия', officialWarrantyDesc: 'Каждый ноутбук поставляется с гарантией производителя, действующей в Таджикистане.',
    fastDelivery: 'Быстрая доставка', fastDeliveryDesc: 'Доставка по Душанбе за одну неделю и надёжная доставка по всей стране.',
    laptopCatalog: 'Каталог', catalogSuffix: 'ноутбуков',
    found: 'найдено', laptopWord: 'ноутбук',
    priceInTJS: 'Цена (TJS)', filtersLabel: 'Фильтры', brand: 'Бренд', ram: 'Оперативная память',
    resetFilters: 'Сбросить все фильтры', showFilters: 'Показать фильтры', hideFilters: 'Скрыть фильтры', active: 'Активен',
    noLaptopsFound: 'Ноутбуки не найдены', tryChangingFilters: 'Попробуйте изменить фильтры или поисковый запрос.',
    recommendedForYou: 'Рекомендуемые модели',
    inStock: 'в наличии', outOfStock: 'Нет в наличии', buy: 'Купить', warranty: 'мес. гарантия',
    backToCatalog: '← Назад в каталог', specifications: 'Характеристики',
    processor: 'Процессор', memory: 'Оперативная память', storage: 'Накопитель', graphics: 'Видеокарта',
    warrantyLabel: 'Гарантия', keyboardLayout: 'Клавиатура',
    addToCart: 'Купить', outOfStockBtn: 'Нет в наличии',
    descriptionLabel: 'Описание', relatedLaptops: 'Вам также может понравиться',
    guarantee: 'Гарантия 12–24 месяца', deliveryCity: 'Доставка по Душанбе', modelsCount: '22+ модели',
    notifTitle: 'Уведомления',
    notif1Title: 'Добавлены новые ноутбуки!', notif1Desc: 'MSI Pulse 15 и MacBook Pro M3 теперь в наличии',
    notif2Title: 'Снижение цены на Acer Aspire 3', notif2Desc: 'Теперь от 4 990 TJS',
    notif3Title: 'Бесплатная доставка по Душанбе', notif3Desc: 'На все заказы на этой неделе',
    months: 'мес', monthsFull: 'месяцев',
    installmentLabel: 'Варианты рассрочки',
    monthsText: 'месяцев',
    monthlyPay: 'Ежемесячный платеж',
    paymentPartner: 'Выберите партнера для оплаты',
    payMethodAlif: 'Рассрочка через Alif Salom (до 24 месяцев) или быстрая оплата через Alif Mobi.',
    payMethodHumo: 'Оплата в рассрочку по карте Humo или мгновенно через Humo Online.',
    payMethodEskhata: 'Рассрочка и быстрые платежи по сканированию через Эсхата Мобайл.',
    payMethodDC: 'Отсканируйте QR-код для мгновенной оплаты через кошелек Dushanbe City.',
    login: 'Войти', signup: 'Регистрация', logout: 'Выйти',
    emailLabel: 'Email', passwordLabel: 'Пароль', confirmPasswordLabel: 'Подтвердите пароль',
    noAccount: 'Нет аккаунта?', haveAccount: 'Уже есть аккаунт?',
    createAccount: 'Создать аккаунт', welcomeBack: 'С возвращением',
    loginToContinue: 'Войдите, чтобы управлять своим брендом и объявлениями.',
    signupToStart: 'Создайте аккаунт, чтобы начать продавать свой бренд ноутбуков.',
    passwordsNoMatch: 'Пароли не совпадают',
    myProfile: 'Мой профиль', memberSince: 'Регистрация', accountInfo: 'Информация об аккаунте',
    myListings: 'Мои объявления', addLaptopListing: 'Добавить объявление',
    brandName: 'Название бренда', modelNameLabel: 'Название модели', cpuLabel: 'Процессор', gpuLabel: 'Видеокарта (необязательно)',
    ramLabel: 'RAM (ГБ)', storageLabel: 'Накопитель (ГБ)', priceLabel: 'Цена (TJS)',
    stockLabel: 'Количество на складе', warrantyMonthsLabel: 'Гарантия (месяцев)', keyboardLayoutLabel: 'Раскладка клавиатуры',
    descriptionOptional: 'Описание (необязательно)', submitListing: 'Добавить',
    submitting: 'Добавление…', listingAdded: 'Объявление добавлено!', noListingsYet: 'Вы пока не добавили ни одного ноутбука.',
    requiredField: 'Обязательное поле',
    invalidCredentials: 'Неверный email или пароль', signupFailed: 'Не удалось создать аккаунт. Возможно, email уже занят.',
    listingFailed: 'Не удалось добавить объявление. Проверьте поля и попробуйте снова.',
    adminPanel: 'Панель администратора', manageListings: 'Объявления', manageUsers: 'Пользователи',
    ownerLabel: 'Владелец', actionsLabel: 'Действия', editAction: 'Изменить', deleteAction: 'Удалить',
    saveAction: 'Сохранить', cancelAction: 'Отмена',
    confirmDeleteListing: 'Удалить это объявление? Это действие нельзя отменить.',
    confirmDeleteUser: 'Удалить этого пользователя? Это действие нельзя отменить.',
    activateAction: 'Активировать', deactivateAction: 'Деактивировать',
    makeAdminAction: 'Сделать админом', revokeAdminAction: 'Снять права админа',
    statusLabel: 'Статус', roleLabel: 'Роль', adminRole: 'Админ', userRole: 'Пользователь', youLabel: '(вы)',
    noListingsAdmin: 'Объявлений пока нет.', noUsersFound: 'Пользователи не найдены.', inactiveLabel: 'Неактивен',
    usernameLabel: 'Имя пользователя', phoneLabel: 'Номер телефона', addressLabel: 'Адрес',
    usernameAvailable: 'Имя пользователя свободно', usernameTaken: 'Имя занято. Попробуйте:',
    checkingUsername: 'Проверка…', saveProfile: 'Сохранить', profileUpdated: 'Профиль обновлён.',
    profileUpdateFailed: 'Не удалось обновить профиль.',
    myBrands: 'Мои бренды', registerBrand: 'Зарегистрировать бренд', noBrandsYet: 'Вы пока не зарегистрировали бренд.',
    registerBrandFirst: 'Зарегистрируйте бренд перед добавлением объявления.',
    brandOnboardingTitle: 'Регистрация бренда', brandOnboardingDesc: 'Расскажите о своём бренде, чтобы покупатели знали, с кем имеют дело.',
    contactPhoneLabel: 'Контактный телефон', supportEmailLabel: 'Email поддержки', brandDescriptionLabel: 'Описание бренда',
    submitBrand: 'Зарегистрировать', brandRegistered: 'Бренд зарегистрирован!', brandRegisterFailed: 'Не удалось зарегистрировать бренд.',
    selectBrand: 'Выберите бренд', quantityLabel: 'Количество', recordSale: 'Записать продажу', saleRecorded: 'Продажа записана!',
    saleRecordFailed: 'Не удалось записать продажу.',
    overviewTab: 'Обзор', totalRevenue: 'Общий доход', totalSales: 'Всего продаж', totalListings: 'Всего объявлений',
    aiAssistant: 'ИИ-Ассистент',
    totalUsers: 'Всего пользователей', revenueTrend: 'Динамика дохода', brandPerformance: 'Эффективность брендов',
    myStatsTitle: 'Статистика моего бренда', myStatsDesc: 'Только по вашим собственным объявлениям.',
    notificationsEmpty: 'Уведомлений пока нет.', noSalesDataYet: 'Пока нет данных о продажах.',
    noUsernameSet: 'имя пользователя не задано',
  },
  tj: {
    home: 'Хона', catalog: 'Каталог',
    searchPlaceholder: 'Ҷустуҷӯ бо бренд, модел ё CPU…',
    lightMode: 'Равшан', darkMode: 'Торик', profile: 'Профил',
    badge: 'Платформаи лаптопии Тоҷикистон',
    heroTitle1: 'Лаптопи беҳтарин', heroTitle2: 'бо нархи сомонӣ', heroTitle3: 'дар Тоҷикистон',
    heroDesc: 'Somon Comp — бозори лаптопҳои ҷаҳонӣ дар Тоҷикистон. Нархи аниқ бо сомонӣ, кафолати расмӣ, ва таҳвили зуд.',
    viewCatalog: 'Каталогро бин', learnMore: 'Бештар бидон',
    weekOffer: 'Пешниҳоди ҳафта', available: 'Дастрас', viewAll: 'Ҳамаро бин →',
    modelsInStock: 'Модел дар анбор', topBrands: 'Брендҳои беҳтарин', avgWarranty: 'Кафолати миёна', localCurrency: 'Асъори маҳаллӣ',
    popular: 'Маъмул', topSales: 'Лаптопҳои Top Sales',
    whySomon: 'Чаро Somon Comp', lessProblems: 'Камтар мушкил.', moreLaptops: 'Бештар лаптоп.', allInOnePlace: 'Ҳама чиз дар як ҷой ва равшан.',
    somoniPrice: 'Нархи сомонӣ', somoniPriceDesc: 'Нархи равшан бо сомонӣ, бидуни ягон хароҷоти пинҳонии воридотӣ.',
    officialWarranty: 'Кафолати расмӣ', officialWarrantyDesc: 'Ҳар лаптоп бо кафолати истеҳсолкунанда дар Тоҷикистон интиқол меёбад.',
    fastDelivery: 'Таҳвили зуд', fastDeliveryDesc: 'Таҳвили ҳафтаӣ дар Душанбе ва фиристодани боэтимод ба саросари кишвар.',
    laptopCatalog: 'Каталоги', catalogSuffix: 'лаптопҳо',
    found: 'ёфт шуд', laptopWord: 'лаптоп',
    priceInTJS: 'Нарх (TJS)', filtersLabel: 'Фильтрҳо', brand: 'Бренд', ram: 'RAM',
    resetFilters: 'Ҳамаи фильтрҳоро тоза кун', showFilters: 'Фильтрҳоро нишон деҳ', hideFilters: 'Фильтрҳоро пинҳон кун', active: 'Фаъол',
    noLaptopsFound: 'Лаптоп ёфт нашуд', tryChangingFilters: 'Фильтр ё калимаи ҷустуҷӯро тағйир диҳед.',
    recommendedForYou: 'Моделҳои тавсияшаванда',
    inStock: 'дастрас', outOfStock: 'Тамом шуд', buy: 'Харидан', warranty: 'мо кафолат',
    backToCatalog: '← Ба каталог', specifications: 'Хусусиятҳо',
    processor: 'Протсессор', memory: 'Хотира', storage: 'Нигаҳдорӣ', graphics: 'Графика',
    warrantyLabel: 'Кафолат', keyboardLayout: 'Клавиатура',
    addToCart: 'Харидан', outOfStockBtn: 'Тамом шуд',
    descriptionLabel: 'Тавсиф', relatedLaptops: 'Инчунин мумкин аст хуш оед',
    guarantee: 'Кафолат 12–24 моҳ', deliveryCity: 'Таҳвил дар Душанбе', modelsCount: '22+ модел',
    notifTitle: 'Огоҳиномаҳо',
    notif1Title: 'Лаптопҳои нав илова шуданд!', notif1Desc: 'MSI Pulse 15 ва MacBook Pro M3 акнун дастрасанд',
    notif2Title: 'Нархи Acer Aspire 3 кам шуд', notif2Desc: 'Акнун аз 4,990 TJS',
    notif3Title: 'Таҳвили ройгон дар Душанбе', notif3Desc: 'Барои ҳамаи фармоишҳои ин ҳафта',
    months: 'мо', monthsFull: 'моҳ',
    installmentLabel: 'Пешниҳодҳои қисм-қисм',
    monthsText: 'моҳ',
    monthlyPay: 'Пардохти моҳона',
    paymentPartner: 'Интихоби шарики пардохт',
    payMethodAlif: 'Пардохти қисм-қисм бо Alif Salom (то 24 моҳ) ё пардохти фаврӣ бо Alif Mobi.',
    payMethodHumo: 'Пардохти қисм-қисм бо корти Humo ё фаврӣ бо Humo Online.',
    payMethodEskhata: 'Пардохти қисм-қисм ва пардохтҳои фаврӣ бо сканер тавассути Эсхата Мобайл.',
    payMethodDC: 'Скани QR-код барои пардохти фаврӣ бо ҳамёни Dushanbe City.',
    login: 'Воридшавӣ', signup: 'Бақайдгирӣ', logout: 'Баромадан',
    emailLabel: 'Email', passwordLabel: 'Парол', confirmPasswordLabel: 'Паролро тасдиқ кунед',
    noAccount: 'Ҳисоб надоред?', haveAccount: 'Аллакай ҳисоб доред?',
    createAccount: 'Сохтани ҳисоб', welcomeBack: 'Хуш омадед',
    loginToContinue: 'Барои идоракунии бренд ва эълонҳои худ ворид шавед.',
    signupToStart: 'Барои фурӯши бренди лаптопии худ ҳисоб созед.',
    passwordsNoMatch: 'Паролҳо мувофиқ нестанд',
    myProfile: 'Профили ман', memberSince: 'Аз санаи', accountInfo: 'Маълумоти ҳисоб',
    myListings: 'Эълонҳои ман', addLaptopListing: 'Иловаи эълон',
    brandName: 'Номи бренд', modelNameLabel: 'Номи модел', cpuLabel: 'Протсессор', gpuLabel: 'Графика (ихтиёрӣ)',
    ramLabel: 'RAM (ГБ)', storageLabel: 'Нигаҳдорӣ (ГБ)', priceLabel: 'Нарх (TJS)',
    stockLabel: 'Миқдор дар анбор', warrantyMonthsLabel: 'Кафолат (моҳ)', keyboardLayoutLabel: 'Тартиби клавиатура',
    descriptionOptional: 'Тавсиф (ихтиёрӣ)', submitListing: 'Илова кардан',
    submitting: 'Иловашуда истодааст…', listingAdded: 'Эълон илова шуд!', noListingsYet: 'Шумо то ҳол ягон лаптоп илова накардаед.',
    requiredField: 'Ҳатмист',
    invalidCredentials: 'Email ё парол нодуруст аст', signupFailed: 'Ҳисоб сохта нашуд. Шояд email аллакай истифода шудааст.',
    listingFailed: 'Эълон илова нашуд. Майдонҳоро санҷида, дубора кӯшиш кунед.',
    adminPanel: 'Панели маъмур', manageListings: 'Эълонҳо', manageUsers: 'Корбарон',
    ownerLabel: 'Соҳиб', actionsLabel: 'Амалҳо', editAction: 'Таҳрир', deleteAction: 'Нест кардан',
    saveAction: 'Нигоҳ доштан', cancelAction: 'Бекор кардан',
    confirmDeleteListing: 'Ин эълонро нест кунам? Баргардонидан мумкин нест.',
    confirmDeleteUser: 'Ин корбарро нест кунам? Баргардонидан мумкин нест.',
    activateAction: 'Фаъол кардан', deactivateAction: 'Ғайрифаъол кардан',
    makeAdminAction: 'Маъмур таъин кардан', revokeAdminAction: 'Ҳуқуқи маъмуриро гирифтан',
    statusLabel: 'Вазъият', roleLabel: 'Рол', adminRole: 'Маъмур', userRole: 'Корбар', youLabel: '(шумо)',
    noListingsAdmin: 'Ҳанӯз эълон нест.', noUsersFound: 'Корбар ёфт нашуд.', inactiveLabel: 'Ғайрифаъол',
    usernameLabel: 'Номи корбар', phoneLabel: 'Рақами телефон', addressLabel: 'Суроға',
    usernameAvailable: 'Номи корбар озод аст', usernameTaken: 'Ин ном гирифта шудааст. Кӯшиш кунед:',
    checkingUsername: 'Санҷида истодааст…', saveProfile: 'Нигоҳ доштан', profileUpdated: 'Профил навсозӣ шуд.',
    profileUpdateFailed: 'Профил навсозӣ нашуд.',
    myBrands: 'Брендҳои ман', registerBrand: 'Бренд сабт кардан', noBrandsYet: 'Шумо ҳанӯз бренд сабт накардаед.',
    registerBrandFirst: 'Пеш аз иловаи эълон бренд сабт кунед.',
    brandOnboardingTitle: 'Сабти бренд', brandOnboardingDesc: 'Дар бораи бренди худ нақл кунед, то харидорон шуморо бишносанд.',
    contactPhoneLabel: 'Телефони тамос', supportEmailLabel: 'Email-и дастгирӣ', brandDescriptionLabel: 'Тавсифи бренд',
    submitBrand: 'Сабт кардан', brandRegistered: 'Бренд сабт шуд!', brandRegisterFailed: 'Бренд сабт нашуд.',
    selectBrand: 'Брендро интихоб кунед', quantityLabel: 'Миқдор', recordSale: 'Сабти фурӯш', saleRecorded: 'Фурӯш сабт шуд!',
    saleRecordFailed: 'Фурӯш сабт нашуд.',
    overviewTab: 'Хулоса', totalRevenue: 'Даромади умумӣ', totalSales: 'Ҳамаи фурӯшҳо', totalListings: 'Ҳамаи эълонҳо',
    aiAssistant: 'Ёвари АИ',
    totalUsers: 'Ҳамаи корбарон', revenueTrend: 'Тағйироти даромад', brandPerformance: 'Натиҷаи брендҳо',
    myStatsTitle: 'Омори бренди ман', myStatsDesc: 'Танҳо барои эълонҳои худи шумо.',
    notificationsEmpty: 'Огоҳинома нест.', noSalesDataYet: 'Ҳанӯз маълумоти фурӯш нест.',
    noUsernameSet: 'номи корбар таъин нашудааст',
  },
} as const;

export type TranslationKeys = keyof typeof T['en'];
type Translations = typeof T;

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKeys) => string;
}

const LangContext = createContext<LangContextType>({
  lang: 'tj',
  setLang: () => {},
  t: (k) => k,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    try {
      const s = localStorage.getItem('sc-lang') as Lang;
      return s && ['tj','ru','en'].includes(s) ? s : 'tj';
    } catch { return 'tj'; }
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('sc-lang', l);
  };

  const t = (key: TranslationKeys): string =>
    (T[lang] as Translations[Lang])[key] as string;

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
