"""Add phones table and relate with orders and sales

Revision ID: a1ac36548676
Revises: c5bb767fec81
Create Date: 2026-06-29 00:51:34.337824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ac36548676'
down_revision: Union[str, Sequence[str], None] = 'c5bb767fec81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('cpu', sa.String(length=100), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('screen_size_inches', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('battery_capacity_mah', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('price_tjs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('warranty_months', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phones_brand'), 'phones', ['brand'], unique=False)
    op.create_index(op.f('ix_phones_brand_id'), 'phones', ['brand_id'], unique=False)
    op.create_index(op.f('ix_phones_model_name'), 'phones', ['model_name'], unique=False)
    op.create_index(op.f('ix_phones_owner_id'), 'phones', ['owner_id'], unique=False)
    op.add_column('orders', sa.Column('phone_id', sa.Integer(), nullable=True))
    op.alter_column('orders', 'laptop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_orders_phone_id'), 'orders', ['phone_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'phones', ['phone_id'], ['id'])
    op.add_column('sales', sa.Column('phone_id', sa.Integer(), nullable=True))
    op.alter_column('sales', 'laptop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_sales_phone_id'), 'sales', ['phone_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'phones', ['phone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_phone_id'), table_name='sales')
    op.alter_column('sales', 'laptop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sales', 'phone_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_phone_id'), table_name='orders')
    op.alter_column('orders', 'laptop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'phone_id')
    op.drop_index(op.f('ix_phones_owner_id'), table_name='phones')
    op.drop_index(op.f('ix_phones_model_name'), table_name='phones')
    op.drop_index(op.f('ix_phones_brand_id'), table_name='phones')
    op.drop_index(op.f('ix_phones_brand'), table_name='phones')
    op.drop_table('phones')
    # ### end Alembic commands ###
